/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserView;
import fuzzysets.CreateJFreeChart;
import fuzzysets.FuzzyOperations;
import java.awt.Color;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
/**
 *
 * @author Bayot
 */
public class FuzzyCalculus extends javax.swing.JFrame {
    FuzzyOperations fuzz = new FuzzyOperations();
    CreateJFreeChart cjfc = new CreateJFreeChart();
    private int xy, xx;
    //InputData in = new InputData();

    /**
     * Creates new form FuzzyCalculus
     */
    public FuzzyCalculus() {
        initComponents();
        getContentPane().setBackground(new Color(42,27,48));
        setLocationRelativeTo(this);
        this.setExtendedState(FuzzyCalculus.MAXIMIZED_BOTH);
    }
    
    private void generateGraph(){
        final XYSeries serie1 = new XYSeries("Conjunto A");
        serie1.add(WIDTH, WIDTH);
    }
    
    private void proof(){
        System.out.println("El primer elemento del arreglo del conjunto es:");
        System.out.println(fuzz.getAnumber());
    }
    
    private void back(){
        this.setVisible(false);
        fuzz.backToNew();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GraphPanel = new javax.swing.JPanel();
        GraphLevel = new javax.swing.JLabel();
        GraphPanelComplement = new javax.swing.JPanel();
        GraphLavelComplement = new javax.swing.JLabel();
        LabelGPFuzzy = new javax.swing.JLabel();
        LabelGPFuzzyB = new javax.swing.JLabel();
        LabelGPFuzzyUnion = new javax.swing.JLabel();
        LabelGPFuzzyInterseccion = new javax.swing.JLabel();
        LabelGPFuzzyComplementoA = new javax.swing.JLabel();
        LabelGPFuzzyComplementoB = new javax.swing.JLabel();
        JlabelBackToNew = new javax.swing.JLabel();
        JlabelExitProcedures = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 708));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        GraphPanel.setBackground(new java.awt.Color(42, 27, 48));

        javax.swing.GroupLayout GraphPanelLayout = new javax.swing.GroupLayout(GraphPanel);
        GraphPanel.setLayout(GraphPanelLayout);
        GraphPanelLayout.setHorizontalGroup(
            GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GraphLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );
        GraphPanelLayout.setVerticalGroup(
            GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GraphLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GraphPanelComplement.setBackground(new java.awt.Color(42, 27, 48));

        javax.swing.GroupLayout GraphPanelComplementLayout = new javax.swing.GroupLayout(GraphPanelComplement);
        GraphPanelComplement.setLayout(GraphPanelComplementLayout);
        GraphPanelComplementLayout.setHorizontalGroup(
            GraphPanelComplementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GraphPanelComplementLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GraphLavelComplement, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        GraphPanelComplementLayout.setVerticalGroup(
            GraphPanelComplementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanelComplementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GraphLavelComplement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        LabelGPFuzzy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelGPFuzzy.setForeground(new java.awt.Color(255, 255, 255));

        LabelGPFuzzyB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelGPFuzzyB.setForeground(new java.awt.Color(255, 255, 255));

        LabelGPFuzzyUnion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelGPFuzzyUnion.setForeground(new java.awt.Color(255, 255, 255));

        LabelGPFuzzyInterseccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelGPFuzzyInterseccion.setForeground(new java.awt.Color(255, 255, 255));

        LabelGPFuzzyComplementoA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelGPFuzzyComplementoA.setForeground(new java.awt.Color(255, 255, 255));

        LabelGPFuzzyComplementoB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelGPFuzzyComplementoB.setForeground(new java.awt.Color(255, 255, 255));

        JlabelBackToNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconmonstr-arrow-64-32.png"))); // NOI18N
        JlabelBackToNew.setToolTipText("Atrás");
        JlabelBackToNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelBackToNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelBackToNewMouseClicked(evt);
            }
        });

        JlabelExitProcedures.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconmonstr-x-mark-3-32.png"))); // NOI18N
        JlabelExitProcedures.setToolTipText("Salir");
        JlabelExitProcedures.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelExitProcedures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelExitProceduresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addComponent(GraphPanelComplement, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JlabelBackToNew, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LabelGPFuzzyUnion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                        .addComponent(LabelGPFuzzyB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelGPFuzzy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JlabelExitProcedures))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelGPFuzzyInterseccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelGPFuzzyComplementoB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelGPFuzzyComplementoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlabelBackToNew)
                    .addComponent(JlabelExitProcedures))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GraphPanelComplement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelGPFuzzyComplementoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelGPFuzzy, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelGPFuzzyComplementoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelGPFuzzyB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelGPFuzzyUnion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelGPFuzzyInterseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JlabelBackToNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelBackToNewMouseClicked
        // TODO add your handling code here:
        //aqui debemos de abrir la otra ventana
        back();
    }//GEN-LAST:event_JlabelBackToNewMouseClicked

    private void JlabelExitProceduresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelExitProceduresMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JlabelExitProceduresMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        //freame mouse pressed
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_formMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuzzyCalculus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuzzyCalculus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuzzyCalculus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuzzyCalculus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuzzyCalculus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel GraphLavelComplement;
    public static javax.swing.JLabel GraphLevel;
    public static javax.swing.JPanel GraphPanel;
    public static javax.swing.JPanel GraphPanelComplement;
    private javax.swing.JLabel JlabelBackToNew;
    private javax.swing.JLabel JlabelExitProcedures;
    public static javax.swing.JLabel LabelGPFuzzy;
    public static javax.swing.JLabel LabelGPFuzzyB;
    public static javax.swing.JLabel LabelGPFuzzyComplementoA;
    public static javax.swing.JLabel LabelGPFuzzyComplementoB;
    public static javax.swing.JLabel LabelGPFuzzyInterseccion;
    public static javax.swing.JLabel LabelGPFuzzyUnion;
    // End of variables declaration//GEN-END:variables
}
